MvcAzureBlobs/Models/ErrorViewModel.cs
namespace MvcAzureBlobs.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcAzureBlobs/Models/ModeloAzureBlobs.cs
namespace MvcAzureBlobs.Models
{
    public class ModeloAzureBlobs
    {
        public string Nombre { get; set; }
        public string Url { get; set; }
    }
}

MvcAzureBlobs/Controllers/BlobController.cs
using Microsoft.AspNetCore.Mvc;
using MvcAzureBlobs.Models;
using MvcAzureBlobs.Services;

namespace MvcAzureBlobs.Controllers
{
    public class BlobController : Controller
    {
        private ServiceStorageBlobs service;
        public BlobController(ServiceStorageBlobs service)
        {
            this.service = service;
        }

        public IActionResult SubirImagen()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SubirImagen(IFormFile file)
        {
            using (Stream stream = file.OpenReadStream())
            {
                await this.service.UploadBlobAsync("contenedorpublico", file.FileName, stream);
            }

            return RedirectToAction("Imagenes");
        }



        public async Task<IActionResult> Imagenes()
        {
            List<ModeloAzureBlobs> modelpublico = await this.service.GetBlobsAsync("contenedorpublico");
            ViewData["PUBLICO"] = modelpublico;
            List<ModeloAzureBlobs> modelprivado = await this.service.GetBlobsAsync("contenedorprivado");
            ViewData["PRIVADO"] = modelprivado;
            return View();
        }

        public async Task<IActionResult> MoverPublico(string nombre)
        {
            await this.service.MoveBlobs("contenedorprivado", "contenedorpublico", nombre);
            return RedirectToAction("Imagenes");
        }

        public async Task<IActionResult> MoverPrivado(string nombre)
        {
            await this.service.MoveBlobs("contenedorpublico", "contenedorprivado", nombre);
            return RedirectToAction("Imagenes");
        }

        
    }
}

MvcAzureBlobs/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcAzureBlobs.Models;
using System.Diagnostics;

namespace MvcAzureBlobs.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcAzureBlobs/Views/Blob/Imagenes.cshtml
@{
    List<ModeloAzureBlobs> blobpublico = ViewData["PUBLICO"] as List<ModeloAzureBlobs>;
    List<ModeloAzureBlobs> blobprivado = ViewData["PRIVADO"] as List<ModeloAzureBlobs>;
}

<a asp-action="SubirImagen" asp-controller="Blob">Subir imagen a contenedor publico</a>

<h1 style="color:red">Imagenes Contenedor Publico</h1>
@if (blobpublico.Count > 0)
{
    @foreach (ModeloAzureBlobs modelpublico in blobpublico)
    {
        <h1 style="color:blue">@modelpublico.Nombre</h1>
        <img src="@modelpublico.Url" style="width:150px;height:150px" />
        <a asp-action="MoverPrivado" asp-controller="Blob" asp-route-nombre="@modelpublico.Nombre">Mover a contenedor privado</a>

    }

}
else
{
    <h2 style="color:black">No hay imagenes en el contenedor publico</h2>
}


<h1 style="color:red">Imagenes Contenedor Privado</h1>
@if (blobprivado.Count > 0)
{
    @foreach (ModeloAzureBlobs modelprivado in blobprivado)
    {
        <h1 style="color:blue">@modelprivado.Nombre</h1>
        <img src="@modelprivado.Url" style="width:150px;height:150px" />
        <a asp-action="MoverPublico" asp-controller="Blob" asp-route-nombre="@modelprivado.Nombre">Mover a contenedor publico</a>
    }

}
else
{
    <h2 style="color:black">No hay imagenes en el contenedor privado</h2>
}

MvcAzureBlobs/Views/Blob/SubirImagen.cshtml
<h1 style="color:red">Subir imagenes a contenedor publico</h1>
<form method="post" enctype="multipart/form-data">
    <label>Seleccione un fichero</label>
    <input type="file" name="file" />
    <br />
    <button type="submit" class="btn btn-dark">
        Subir archivo
    </button>
</form>

MvcAzureBlobs/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcAzureBlobs/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcAzureBlobs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcAzureBlobs.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcAzureBlobs</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blob" asp-action="Imagenes">Imagenes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcAzureBlobs - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>